### ISSUE TITLE
نمونه

### ISSUE THREAD

**Issue by ho33ein74** [mhmmdq/ecommerce-api-post-ir#2]
سلام وقت بخیر
اگر ممکن است یک نمونه هم ازش بزارید تشکر

**Comment by mhmmdq** [comment]
سلام دوست من چشم
درحال حاظر درحال توسعه افزونه ای وردپرس براش هستم بعد از اتمام پروژه رو به صورت عمومی در دسترس قرار میدم و لینکش رو توی انتهای توضیحات میزارم
